---
title: "Homework 5 from Lab 4"
output: github_document
---


### Econ B2000, MA Econometrics
### Kevin R Foster, the Colin Powell School at the City College of New York, CUNY
### Fall 2024
### Due 8am EST Friday Sept 27



*Each student should submit a separate assignment, even if it is an identical computer file to the rest of your study group. When submitting assignments, please include your name and the assignment number as part of the filename. Please write the names of your study group members at the beginning of your homework.*


1. What are the names of the people in your study group?
2. Write up the results of your lab work. Highlight the good stuff. Then go into more detail, explaining each step (for instance, your sample choice). Form several hypothesis tests about interesting variables. Please provide both a p-value for the hypothesis test and a confidence interval and include a short paragraph explaining each test (carefully noting what is the null hypothesis) and explaining the results of that test. 

